console.log(typeof Boolean)
console.log(typeof Map)
console.log(typeof Function)
console.log(typeof Object)
console.log(typeof new Object)
console.log(typeof Array)
console.log(typeof Symbol)
console.log(typeof 5)
console.log(typeof Number)
console.log(typeof "tatata")
console.log(typeof String)
console.log("1"+"2")
